name: Build-Deploy-User
on:
  pull_request:
    branches: [ "main" ]
    push:
      branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew build

      - name: Login
        uses: azure/docker-login@v1
        with:
          login-server: chatwebappcontainerregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build and Push
        run: |
          docker build . -t chatwebappcontainerregistry.azurecr.io/chatapp-user:${{ github.sha }}
          docker push chatwebappcontainerregistry.azurecr.io/chatapp-user:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update --name chatapp-userservice \
            --resource-group EXR-DEV-QA \
            --image chatwebappcontainerregistry.azurecr.io/chatapp-user:${{ github.sha }}